language: cpp

sudo: false

addons:
  apt:
    sources: boost-latest 
    packages:
      - ccache
      - libfftw3-dev
      - cmake
      - doxygen
      - libopenmpi-dev
      - openmpi-bin
      - libboost1.55-all-dev
      - python-sphinx
      - python-matplotlib

before_install:
 - if [[ ${BUILD_UG} ]]; then git clone https://github.com/espressopp/espressopp.github.io.git doc/ug/_build/html; fi
 - mkdir -p "$HOME/bin"
 - if [[ ${CMAKE_VERSION} ]]; then wget --no-check-certificate -qO- http://www.cmake.org/files/v${CMAKE_VERSION:0:3}/cmake-${CMAKE_VERSION}.tar.gz | tar -xz && ln -s $PWD/cmake-${CMAKE_VERSION}/bin/cmake "$HOME/bin/cmake"; fi
 - ln -s /usr/bin/ccache "$HOME/bin/clang++"
 - ln -s /usr/bin/ccache "$HOME/bin/clang"
 - if [[ ${EXTERNAL} = ON ]]; then pip install --user mpi4py==1.3.1; fi 

env: #maybe add mpich later
  global:
    - CCACHE_CPP2=yes
  matrix:
    - EXTERNAL=ON BUILD_UG=ON CMAKE_VERSION=3.1.3-Linux-x86_64
    - EXTERNAL=OFF

script:
  - mkdir build && cd build && 
    PATH="$HOME/bin:/usr/lib/ccache:$PATH" cmake -DEXTERNAL_BOOST=$EXTERNAL -DEXTERNAL_MPI4PY=$EXTERNAL .. && 
    make -j4 all ${BUILD_UG:+ug} &&
    make test ARGS="-V" &&
    make install DESTDIR="${HOME}"

after_success:
  - if [[ ${BUILD_UG} = ON && ${TRAVIS_JOB_NUMBER} = *.1 ]]; then
      cd ../doc/ug/_build/html/;
      if [[ ${TRAVIS_BRANCH} = master && ${encrypted_194b3d1e9306_key} && ${encrypted_194b3d1e9306_iv} && ${TRAVIS_PULL_REQUEST} == false ]]; then
        git config --global user.name "Automatic Deployment (Travis CI)";
        git config --global user.email "espp-devel@listserv.mpip-mainz.mpg.de";
        git add --all && git commit -m "Documentation Update";
        openssl aes-256-cbc -K $encrypted_194b3d1e9306_key -iv $encrypted_194b3d1e9306_iv -in ../../deploy.enc -out ~/.ssh/id_rsa -d;
        chmod 600 ~/.ssh/id_rsa;
        git push git@github.com:espressopp/espressopp.github.io.git master;
      else
        git diff --no-color;
      fi;
    fi

cache:
  directories:
    - $HOME/.ccache

compiler:
  - clang
  - gcc

addons:
  code_climate:
   repo_token: 74ff64a9c455ce02fc2b30eac0a40b86c331585185742d1045f40299260f032c
